### ISSUE TITLE
Why do we have an Estate module?

### ISSUE THREAD

**Issue by Samshal** [houseafrica/kubo-plugins#31]
@Jiggabyte The design goal for project-kubo is to be completely decoupled from whatever user interface it will consumed from, so that it can be the backend for all our products and services at Houseafrica.

https://github.com/houseafrica/kubo-plugins/tree/master/src/Estate is a module you have created.

I believe that these was created to meet some requirements of the sytemap frontend. I think it may be technical debt.

We should consider refactoring this module into a more UI-agnostic one.

**Comment by Jiggabyte** [comment]
I guess I did not understand the decoupled nature completely i wanted to group together everything about estates but I will refactor it later into properties

**Comment by Jiggabyte** [comment]
I have refactored it and removed it from the codebase but most of the endpoints have been transfered to users and properties modules
